"""
User-level feature computation.

Creates one row per user with aggregate features capturing behavior patterns.
"""
import pandas as pd
import numpy as np


def compute_user_features(
    events_df: pd.DataFrame,
    reference_time: pd.Timestamp
) -> pd.DataFrame:
    """
    Compute user-level features from event log.
    
    Args:
        events_df: Event log with columns:
            - user_id
            - event_id
            - product_id
            - session_id
            - event_type ('view', 'add_to_cart', 'purchase')
            - ts_datetime (timezone-aware timestamp)
        reference_time: Reference timestamp for recency computation
    
    Returns:
        DataFrame with one row per user, columns:
            - user_id (str)
            - total_events (int)
            - unique_products_interacted (int)
            - unique_sessions (int)
            - last_event_ts (Timestamp)
            - views_count (int)
            - add_to_cart_count (int)
            - purchase_count (int)
            - recency_days (float)
    
    Feature Definitions:
        - total_events: Total number of events generated by user
        - unique_products_interacted: Number of unique products user has interacted with
        - unique_sessions: Number of unique sessions for user
        - last_event_ts: Timestamp of user's most recent event
        - views_count: Number of view events
        - add_to_cart_count: Number of add-to-cart events
        - purchase_count: Number of purchase events
        - recency_days: Days since last event (measured from reference_time)
    """
    # Basic aggregations per user
    user_features = events_df.groupby('user_id').agg(
        total_events=('event_id', 'count'),
        unique_products_interacted=('product_id', 'nunique'),
        unique_sessions=('session_id', 'nunique'),
        last_event_ts=('ts_datetime', 'max')
    ).reset_index()
    
    # Event type counts per user
    # Create pivot table: rows=user_id, columns=event_type, values=count
    event_type_counts = events_df.groupby(['user_id', 'event_type']).size().unstack(fill_value=0)
    event_type_counts = event_type_counts.reset_index()
    
    # Rename columns to match requirements
    column_mapping = {
        'view': 'views_count',
        'add_to_cart': 'add_to_cart_count',
        'purchase': 'purchase_count'
    }
    
    # Rename existing columns
    event_type_counts = event_type_counts.rename(columns=column_mapping)
    
    # Ensure all required event type columns exist (fill missing with 0)
    for col in ['views_count', 'add_to_cart_count', 'purchase_count']:
        if col not in event_type_counts.columns:
            event_type_counts[col] = 0
    
    # Drop 'click' column if it exists (not used)
    if 'click' in event_type_counts.columns:
        event_type_counts = event_type_counts.drop(columns=['click'])
    
    # Merge event type counts with user features
    user_features = user_features.merge(event_type_counts, on='user_id', how='left')
    
    # Fill any NaN values with 0
    user_features['views_count'] = user_features['views_count'].fillna(0).astype(int)
    user_features['add_to_cart_count'] = user_features['add_to_cart_count'].fillna(0).astype(int)
    user_features['purchase_count'] = user_features['purchase_count'].fillna(0).astype(int)
    
    # Recency: days since last event (from reference time)
    user_features['recency_days'] = (reference_time - user_features['last_event_ts']).dt.total_seconds() / 86400
    
    return user_features
