apiVersion: v1
kind: Secret
metadata:
  name: atlas-secrets
  namespace: atlas
type: Opaque
stringData:
  JWT_SECRET: "devsecret"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "ecommerce"
  POSTGRES_URI: "postgresql://postgres:postgres@postgres:5432/ecommerce"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ecommerce"
  REDIS_URL: "redis://redis:6379"
